<?php

namespace Database\Seeders;

use App\Enums\DegreeLevel;
use App\Enums\FundingType;
use App\Enums\LanguageRequirement;
use App\Enums\ScholarshipStatus;
use App\Models\Scholarship;
use App\Models\User;
use Illuminate\Database\Seeder;

class ScholarshipSeeder extends Seeder
{
    /** مزايا التمويل الكامل — مشتركة بين أغلب المنح الممولة */
    private const FULL_BENEFITS = [
        ['title' => 'تغطية كاملة', 'description' => 'إعفاء كامل من الرسوم الدراسية طوال فترة البرنامج.', 'icon' => 'Wallet'],
        ['title' => 'تذاكر السفر', 'description' => 'تذاكر ذهاب وعودة بدرجة سياحية على حساب الجهة المانحة.', 'icon' => 'Plane'],
        ['title' => 'راتب شهري', 'description' => 'مخصّص شهري كافٍ لتغطية المعيشة والسكن والتأمين الصحي.', 'icon' => 'Coins'],
    ];

    private const PARTIAL_BENEFITS = [
        ['title' => 'تغطية جزئية للرسوم', 'description' => 'خصم يتراوح بين 50% و70% من الرسوم الدراسية.', 'icon' => 'Wallet'],
        ['title' => 'تأمين صحي', 'description' => 'تغطية تأمين صحي أساسي طوال مدة الدراسة.', 'icon' => 'HeartPulse'],
    ];

    private const COMMON_DOCS = [
        ['name' => 'السيرة الذاتية (CV)', 'note' => 'PDF'],
        ['name' => 'السجلات الأكاديمية (Transcripts)', 'note' => 'مترجمة ومعتمدة'],
        ['name' => 'خطابات التوصية', 'note' => 'من أكاديميين'],
        ['name' => 'بيان الغرض الشخصي (SOP)', 'note' => '1000 كلمة'],
        ['name' => 'صورة جواز السفر', 'note' => 'سارية المفعول'],
    ];

    public function run(): void
    {
        $author = User::where('email', 'admin@menhity.com')->firstOrFail();

        foreach ($this->scholarships() as $data) {
            $status = $data['status']
                ?? ($data['deadline_in_days'] < 0 ? ScholarshipStatus::Expired : ScholarshipStatus::Published);

            $scholarship = Scholarship::create([
                'slug' => Scholarship::generateSlug($data['title_en']),
                'title_ar' => $data['title_ar'],
                'title_en' => $data['title_en'],
                'provider' => $data['provider'],
                'university_name' => $data['university_name'] ?? null,
                'country_code' => $data['country_code'],
                'country_name_ar' => $data['country_name_ar'],
                'region' => $data['region'],
                'funding_type' => $data['funding_type'],
                'language_requirement' => $data['language_requirement'],
                'status' => $status,
                'description' => $data['description'],
                'deadline' => now()->addDays($data['deadline_in_days'])->startOfDay(),
                'open_date' => now()->addDays($data['deadline_in_days'] - 120)->startOfDay(),
                'min_gpa' => $data['min_gpa'] ?? null,
                'gpa_scale' => $data['gpa_scale'] ?? null,
                'acceptance_rate' => $data['acceptance_rate'] ?? null,
                'is_featured' => $data['is_featured'] ?? false,
                'created_by_id' => $author->id,
                'published_at' => $status === ScholarshipStatus::Published ? now() : null,
                'views_count' => random_int(50, 950),
            ]);

            foreach ($data['levels'] as $level) {
                $scholarship->levels()->create(['level' => $level]);
            }

            foreach ($data['majors'] as $major) {
                $scholarship->majors()->create(['name' => $major]);
            }

            foreach ($data['eligibility'] as $i => $text) {
                $scholarship->eligibility()->create(['text' => $text, 'sort_order' => $i]);
            }

            foreach ($data['documents'] as $i => $doc) {
                $scholarship->documents()->create([...$doc, 'sort_order' => $i]);
            }

            foreach ($data['benefits'] as $i => $benefit) {
                $scholarship->benefits()->create([...$benefit, 'sort_order' => $i]);
            }
        }

        $this->command->info('✓ تم إنشاء '.Scholarship::count().' منحة');
    }

    /** @return array<int, array<string, mixed>> */
    private function scholarships(): array
    {
        return [
            [
                'title_ar' => 'المنحة الحكومية التركية',
                'title_en' => 'Türkiye Bursları',
                'provider' => 'الحكومة التركية',
                'country_code' => 'TR',
                'country_name_ar' => 'تركيا',
                'region' => 'أوروبا وآسيا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::NotRequired,
                'deadline_in_days' => 42,
                'levels' => [DegreeLevel::Bachelor, DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['الهندسة', 'الطب', 'العلوم الإنسانية', 'إدارة الأعمال', 'هندسة البرمجيات'],
                'min_gpa' => 70, 'gpa_scale' => 100, 'acceptance_rate' => 8, 'is_featured' => true,
                'description' => 'المنحة الحكومية التركية من أوسع برامج المنح في العالم، تقدّمها الحكومة التركية للطلاب الدوليين في مختلف المراحل الدراسية. تشمل المنحة الرسوم الدراسية كاملة، والسكن، والتأمين الصحي، ومخصّصاً شهرياً، إضافة إلى سنة تحضيرية لتعلّم اللغة التركية.',
                'eligibility' => [
                    'أن يكون المتقدّم من غير حاملي الجنسية التركية.',
                    'ألا يتجاوز عمر المتقدّم 21 عاماً للبكالوريوس، و30 عاماً للماجستير، و35 عاماً للدكتوراه.',
                    'الحصول على معدل لا يقل عن 70% للبكالوريوس والماجستير، و75% للدكتوراه.',
                    'ألا يكون المتقدّم طالباً مسجّلاً حالياً في إحدى الجامعات التركية.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة DAAD الألمانية للدراسات العليا',
                'title_en' => 'DAAD Study Scholarships',
                'provider' => 'الهيئة الألمانية للتبادل الأكاديمي (DAAD)',
                'country_code' => 'DE',
                'country_name_ar' => 'ألمانيا',
                'region' => 'أوروبا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 64,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['الهندسة', 'علوم الحاسوب', 'الذكاء الاصطناعي وتعلم الآلة', 'العلوم الطبيعية', 'الاقتصاد'],
                'min_gpa' => 3.0, 'gpa_scale' => 4, 'acceptance_rate' => 12, 'is_featured' => true,
                'description' => 'تقدّم الهيئة الألمانية للتبادل الأكاديمي (DAAD) منحاً للدراسات العليا في الجامعات الألمانية للخريجين المتميّزين من مختلف دول العالم. تركّز المنحة على البرامج البحثية والتخصصات التقنية، وتشمل مخصّصاً شهرياً وتأميناً صحياً ودعماً لتكاليف السفر.',
                'eligibility' => [
                    'الحصول على درجة البكالوريوس بتقدير جيد جداً على الأقل.',
                    'ألا يكون قد مضى على التخرّج أكثر من ست سنوات.',
                    'إتقان اللغة الإنجليزية أو الألمانية بما يتوافق مع لغة البرنامج.',
                    'خبرة عملية لا تقل عن سنتين في بعض البرامج.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة تشيفينينغ البريطانية',
                'title_en' => 'Chevening Scholarships',
                'provider' => 'وزارة الخارجية البريطانية',
                'country_code' => 'GB',
                'country_name_ar' => 'المملكة المتحدة',
                'region' => 'أوروبا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 12,
                'levels' => [DegreeLevel::Master],
                'majors' => ['السياسات العامة', 'إدارة الأعمال', 'القانون', 'الإعلام', 'التنمية المستدامة'],
                'min_gpa' => 3.2, 'gpa_scale' => 4, 'acceptance_rate' => 3, 'is_featured' => true,
                'description' => 'منحة تشيفينينغ هي برنامج المنح الرسمي للحكومة البريطانية، يستهدف القادة الواعدين من مختلف أنحاء العالم لدراسة الماجستير في الجامعات البريطانية. تركّز المنحة على القدرة القيادية وأثر المتقدّم المتوقّع في بلده بعد التخرّج.',
                'eligibility' => [
                    'خبرة عملية لا تقل عن سنتين (2800 ساعة عمل).',
                    'الحصول على درجة البكالوريوس بتقدير يؤهّل للالتحاق ببرنامج ماجستير بريطاني.',
                    'التقديم على ثلاثة برامج ماجستير مختلفة في جامعات بريطانية.',
                    'الالتزام بالعودة إلى بلد الجنسية لمدة سنتين بعد انتهاء المنحة.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'برنامج فولبرايت الأمريكي',
                'title_en' => 'Fulbright Foreign Student Program',
                'provider' => 'وزارة الخارجية الأمريكية',
                'country_code' => 'US',
                'country_name_ar' => 'الولايات المتحدة',
                'region' => 'أمريكا الشمالية',
                'funding_type' => FundingType::Partial,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 95,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['العلوم الاجتماعية', 'الهندسة', 'الصحة العامة', 'علوم البيانات'],
                'min_gpa' => 3.3, 'gpa_scale' => 4, 'acceptance_rate' => 5, 'is_featured' => true,
                'description' => 'برنامج فولبرايت من أعرق برامج التبادل الأكاديمي في العالم، يتيح للطلاب الدوليين إكمال دراساتهم العليا في الجامعات الأمريكية، مع التركيز على التبادل الثقافي والبحث العلمي.',
                'eligibility' => [
                    'درجة البكالوريوس أو ما يعادلها من مؤسسة معترف بها.',
                    'إتقان اللغة الإنجليزية مثبت بشهادة TOEFL أو IELTS.',
                    'خبرة أكاديمية أو مهنية ذات صلة بالتخصص المطلوب.',
                    'الالتزام بالعودة إلى البلد الأم بعد إتمام البرنامج.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::PARTIAL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الحكومة اليابانية MEXT',
                'title_en' => 'MEXT Japanese Government Scholarship',
                'provider' => 'وزارة التعليم اليابانية',
                'country_code' => 'JP',
                'country_name_ar' => 'اليابان',
                'region' => 'آسيا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::NotRequired,
                'deadline_in_days' => 130,
                'levels' => [DegreeLevel::Bachelor, DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['الهندسة', 'الروبوتات', 'علوم الحاسوب', 'الدراسات اليابانية', 'الطب'],
                'min_gpa' => 3.0, 'gpa_scale' => 4, 'acceptance_rate' => 7, 'is_featured' => true,
                'description' => 'تقدّم الحكومة اليابانية منحة MEXT للطلاب الدوليين للدراسة في الجامعات اليابانية. تشمل المنحة الرسوم الدراسية كاملة، ومخصّصاً شهرياً، وتذاكر الطيران، إضافة إلى دورة لغة يابانية تحضيرية.',
                'eligibility' => [
                    'ألا يتجاوز عمر المتقدّم 35 عاماً.',
                    'الحصول على معدل تراكمي مرتفع في المرحلة السابقة.',
                    'الاستعداد لتعلّم اللغة اليابانية.',
                    'عدم حمل الجنسية اليابانية.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة إيراسموس موندوس المشتركة',
                'title_en' => 'Erasmus Mundus Joint Masters',
                'provider' => 'الاتحاد الأوروبي',
                'country_code' => 'EU',
                'country_name_ar' => 'أوروبا (دول متعددة)',
                'region' => 'أوروبا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 78,
                'levels' => [DegreeLevel::Master],
                'majors' => ['علوم البيانات', 'الاستدامة البيئية', 'الهندسة', 'الدراسات الأوروبية'],
                'min_gpa' => 3.0, 'gpa_scale' => 4, 'acceptance_rate' => 10, 'is_featured' => true,
                'description' => 'برامج ماجستير مشتركة تُدرَّس في أكثر من جامعة أوروبية، بتمويل كامل من الاتحاد الأوروبي. يتنقّل الطالب بين دولتين أوروبيتين على الأقل خلال فترة الدراسة، ويحصل على شهادة مشتركة.',
                'eligibility' => [
                    'درجة بكالوريوس في تخصص ذي صلة.',
                    'إتقان اللغة الإنجليزية (IELTS 6.5 أو ما يعادلها).',
                    'خطاب دافع يوضّح سبب اختيار البرنامج المشترك.',
                    'خطابا توصية أكاديميان.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الحكومة الكورية GKS',
                'title_en' => 'Global Korea Scholarship',
                'provider' => 'المعهد الوطني للتعليم الدولي (NIIED)',
                'country_code' => 'KR',
                'country_name_ar' => 'كوريا الجنوبية',
                'region' => 'آسيا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::NotRequired,
                'deadline_in_days' => -20,
                'levels' => [DegreeLevel::Bachelor, DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['الهندسة', 'الدراسات الكورية', 'إدارة الأعمال', 'علوم الحاسوب'],
                'min_gpa' => 80, 'gpa_scale' => 100, 'acceptance_rate' => 6,
                'description' => 'منحة الحكومة الكورية للطلاب الدوليين، تغطّي الرسوم الدراسية والسكن والمخصّص الشهري، مع سنة تحضيرية لتعلّم اللغة الكورية.',
                'eligibility' => [
                    'ألا يتجاوز العمر 25 عاماً للبكالوريوس و40 عاماً للدراسات العليا.',
                    'معدل تراكمي لا يقل عن 80%.',
                    'لياقة صحية تسمح بالدراسة في الخارج.',
                    'عدم الحصول على منحة كورية حكومية سابقة.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة جامعة الملك عبدالله للعلوم والتقنية',
                'title_en' => 'KAUST Fellowship',
                'provider' => 'جامعة الملك عبدالله للعلوم والتقنية',
                'university_name' => 'جامعة الملك عبدالله للعلوم والتقنية (KAUST)',
                'country_code' => 'SA',
                'country_name_ar' => 'السعودية',
                'region' => 'الشرق الأوسط',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 55,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['علوم الحاسوب', 'الطاقة المتجددة المتقدمة', 'علوم البحار', 'الهندسة الكيميائية'],
                'min_gpa' => 3.2, 'gpa_scale' => 4, 'acceptance_rate' => 15,
                'description' => 'منحة بحثية كاملة في جامعة الملك عبدالله للعلوم والتقنية، تشمل الرسوم والسكن والتأمين ومخصّصاً شهرياً سخياً، في بيئة بحثية عالمية المستوى.',
                'eligibility' => [
                    'درجة بكالوريوس في تخصص علمي أو هندسي.',
                    'معدل تراكمي 3.2 من 4.0 كحد أدنى.',
                    'شهادة لغة إنجليزية (IELTS 6.5 أو TOEFL 79).',
                    'خطاب دافع وخطة بحثية مختصرة.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الرئيس لبرامج الدراسات العليا في جامعة هارفارد',
                'title_en' => 'Harvard Presidential Graduate Fellowship',
                'provider' => 'جامعة هارفارد',
                'university_name' => 'جامعة هارفارد',
                'country_code' => 'US',
                'country_name_ar' => 'الولايات المتحدة',
                'region' => 'أمريكا الشمالية',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 12,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['الذكاء الاصطناعي وتعلم الآلة', 'علوم البيانات الحيوية', 'أخلاقيات التكنولوجيا والسياسات', 'الطاقة المتجددة المتقدمة'],
                'min_gpa' => 3.6, 'gpa_scale' => 4, 'acceptance_rate' => 50, 'is_featured' => true,
                'description' => 'تُعد منحة الرئيس في جامعة هارفارد واحدة من أكثر المسارات الأكاديمية مرموقةً عالمياً، حيث تستهدف استقطاب النخبة المتفوّقة وإتاحة الفرصة لهم لقيادة أبحاث عالمية المستوى في مجالات المستقبل. تُغطّي المنحة كامل التكاليف الدراسية وتوفّر بيئة بحثية متكاملة ودعماً مالياً غير مشروط بعمل إضافي.',
                'eligibility' => [
                    'الحصول على درجة البكالوريوس أو الماجستير بتقدير لا يقل عن ممتاز (أو ما يعادلها).',
                    'اجتياز اختبار اللغة الإنجليزية بعلامة معتمدة (TOEFL بحد أدنى 100 أو IELTS بحد أدنى 7.5).',
                    'تقديم خطة بحثية واضحة ومبتكرة تخدم التحديات العلمية المعاصرة.',
                    'خلو السجل الأكاديمي من أي عقوبات تأديبية أو سوابق أكاديمية.',
                ],
                'documents' => [
                    ['name' => 'السيرة الذاتية (CV)', 'note' => 'PDF'],
                    ['name' => 'السجلات الأكاديمية (Transcripts)', 'note' => 'مترجمة ومعتمدة'],
                    ['name' => 'خطابات التوصية', 'note' => '3 خطابات من أكاديميين'],
                    ['name' => 'بيان الغرض الشخصي (SOP)', 'note' => '1000 كلمة'],
                ],
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الحكومة الكندية فانير',
                'title_en' => 'Vanier Canada Graduate Scholarships',
                'provider' => 'الحكومة الكندية',
                'country_code' => 'CA',
                'country_name_ar' => 'كندا',
                'region' => 'أمريكا الشمالية',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 110,
                'levels' => [DegreeLevel::Phd],
                'majors' => ['الصحة العامة', 'العلوم الطبيعية', 'الهندسة', 'العلوم الاجتماعية'],
                'min_gpa' => 3.5, 'gpa_scale' => 4, 'acceptance_rate' => 9,
                'description' => 'منحة فانير الكندية موجّهة لطلاب الدكتوراه المتميّزين على مستوى العالم، وتركّز على التميّز الأكاديمي والقدرة البحثية والإمكانات القيادية.',
                'eligibility' => [
                    'التسجيل في برنامج دكتوراه في جامعة كندية مؤهّلة.',
                    'معدل تراكمي ممتاز في المرحلتين السابقتين.',
                    'ترشيح من الجامعة الكندية المضيفة.',
                    'سجل بحثي موثّق.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الحكومة الأسترالية للتنمية',
                'title_en' => 'Australia Awards Scholarships',
                'provider' => 'الحكومة الأسترالية',
                'country_code' => 'AU',
                'country_name_ar' => 'أستراليا',
                'region' => 'أوقيانوسيا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 88,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['التنمية المستدامة', 'الصحة العامة', 'الزراعة', 'إدارة الأعمال'],
                'min_gpa' => 3.0, 'gpa_scale' => 4, 'acceptance_rate' => 11,
                'description' => 'منح تقدّمها الحكومة الأسترالية للطلاب من الدول النامية، بهدف بناء القدرات وتعزيز الروابط التنموية. تشمل الرسوم كاملة والمعيشة والتأمين الصحي.',
                'eligibility' => [
                    'أن يكون المتقدّم من إحدى الدول المؤهّلة للبرنامج.',
                    'خبرة عملية لا تقل عن سنتين.',
                    'شهادة لغة إنجليزية سارية.',
                    'الالتزام بالعودة للبلد الأم بعد التخرّج.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الحكومة الهولندية أورانج توليب',
                'title_en' => 'Orange Tulip Scholarship',
                'provider' => 'نوفيك الهولندية (Nuffic)',
                'country_code' => 'NL',
                'country_name_ar' => 'هولندا',
                'region' => 'أوروبا',
                'funding_type' => FundingType::Partial,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 33,
                'levels' => [DegreeLevel::Bachelor, DegreeLevel::Master],
                'majors' => ['إدارة الأعمال', 'التصميم', 'الهندسة', 'العلوم الاجتماعية'],
                'min_gpa' => 3.0, 'gpa_scale' => 4, 'acceptance_rate' => 18,
                'description' => 'منحة جزئية تقدّمها المؤسسات الهولندية للطلاب الدوليين، تغطّي جزءاً من الرسوم الدراسية في برامج البكالوريوس والماجستير.',
                'eligibility' => [
                    'قبول مبدئي في إحدى الجامعات الهولندية المشاركة.',
                    'شهادة لغة إنجليزية معتمدة.',
                    'سجل أكاديمي جيد.',
                    'خطاب دافع.',
                ],
                'documents' => array_slice(self::COMMON_DOCS, 0, 4),
                'benefits' => self::PARTIAL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة إيفل الفرنسية للتميّز',
                'title_en' => 'Eiffel Excellence Scholarship',
                'provider' => 'وزارة أوروبا والشؤون الخارجية الفرنسية',
                'country_code' => 'FR',
                'country_name_ar' => 'فرنسا',
                'region' => 'أوروبا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::NotRequired,
                'deadline_in_days' => 25,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['القانون', 'الاقتصاد', 'الهندسة', 'العلوم السياسية'],
                'min_gpa' => 3.2, 'gpa_scale' => 4, 'acceptance_rate' => 14,
                'description' => 'برنامج إيفل للتميّز يستقطب الطلاب الأجانب المتميّزين للدراسة في المؤسسات الفرنسية العليا، ويشمل مخصّصاً شهرياً وتذاكر سفر وتأميناً صحياً.',
                'eligibility' => [
                    'ألا يتجاوز العمر 25 عاماً للماجستير و30 عاماً للدكتوراه.',
                    'ترشيح من المؤسسة الفرنسية المضيفة.',
                    'ألا يكون المتقدّم حاصلاً على منحة فرنسية سابقة.',
                    'تفوّق أكاديمي واضح.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الحكومة الصينية CSC',
                'title_en' => 'Chinese Government Scholarship',
                'provider' => 'مجلس المنح الصيني (CSC)',
                'country_code' => 'CN',
                'country_name_ar' => 'الصين',
                'region' => 'آسيا',
                'funding_type' => FundingType::Full,
                'language_requirement' => LanguageRequirement::NotRequired,
                'deadline_in_days' => 70,
                'levels' => [DegreeLevel::Bachelor, DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['الهندسة', 'الطب', 'الدراسات الصينية', 'علوم الحاسوب', 'التجارة الدولية'],
                'min_gpa' => 75, 'gpa_scale' => 100, 'acceptance_rate' => 20,
                'description' => 'منحة شاملة تقدّمها الحكومة الصينية للطلاب الدوليين في مختلف المراحل، تغطّي الرسوم والسكن والتأمين ومخصّصاً شهرياً.',
                'eligibility' => [
                    'ألا يتجاوز العمر 25 عاماً للبكالوريوس و35 للماجستير و40 للدكتوراه.',
                    'صحة جيدة مثبتة بتقرير طبي.',
                    'معدل تراكمي جيد.',
                    'عدم حمل الجنسية الصينية.',
                ],
                'documents' => self::COMMON_DOCS,
                'benefits' => self::FULL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة جامعة خان الإسبانية',
                'title_en' => 'Khan University Spain Scholarship',
                'provider' => 'مؤسسة خان التعليمية',
                'university_name' => 'جامعة خان',
                'country_code' => 'ES',
                'country_name_ar' => 'إسبانيا',
                'region' => 'أوروبا',
                'funding_type' => FundingType::Partial,
                'language_requirement' => LanguageRequirement::NotRequired,
                'deadline_in_days' => 24,
                'levels' => [DegreeLevel::Master],
                'majors' => ['إدارة الأعمال', 'السياحة والضيافة', 'التصميم'],
                'min_gpa' => 2.8, 'gpa_scale' => 4, 'acceptance_rate' => 25,
                'description' => 'منحة جزئية للدراسات العليا في إسبانيا، تركّز على برامج إدارة الأعمال والتخصصات الإبداعية، وتغطّي جزءاً من الرسوم الدراسية.',
                'eligibility' => [
                    'درجة بكالوريوس معترف بها.',
                    'معدل تراكمي لا يقل عن 2.8 من 4.0.',
                    'خطاب دافع باللغة الإنجليزية أو الإسبانية.',
                    'مقابلة شخصية عن بُعد.',
                ],
                'documents' => array_slice(self::COMMON_DOCS, 0, 3),
                'benefits' => self::PARTIAL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الجامعة الماليزية الدولية',
                'title_en' => 'Malaysia International Scholarship',
                'provider' => 'وزارة التعليم العالي الماليزية',
                'country_code' => 'MY',
                'country_name_ar' => 'ماليزيا',
                'region' => 'آسيا',
                'funding_type' => FundingType::Partial,
                'language_requirement' => LanguageRequirement::Required,
                'deadline_in_days' => 47,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['التكنولوجيا الحيوية', 'الهندسة', 'تكنولوجيا المعلومات', 'الاقتصاد الإسلامي'],
                'min_gpa' => 3.0, 'gpa_scale' => 4, 'acceptance_rate' => 22,
                'description' => 'منحة ماليزية للطلاب الدوليين المتميّزين في برامج الدراسات العليا، تغطّي الرسوم الدراسية ومخصّصاً شهرياً جزئياً.',
                'eligibility' => [
                    'ألا يتجاوز العمر 40 عاماً للماجستير و45 للدكتوراه.',
                    'معدل تراكمي 3.0 من 4.0 كحد أدنى.',
                    'IELTS 6.5 أو ما يعادلها.',
                    'مقترح بحثي للمتقدّمين لبرامج البحث.',
                ],
                'documents' => array_slice(self::COMMON_DOCS, 0, 4),
                'benefits' => self::PARTIAL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة الحكومة الإيطالية للطلاب الدوليين',
                'title_en' => 'Italian Government Scholarship',
                'provider' => 'وزارة الخارجية الإيطالية',
                'country_code' => 'IT',
                'country_name_ar' => 'إيطاليا',
                'region' => 'أوروبا',
                'funding_type' => FundingType::Partial,
                'language_requirement' => LanguageRequirement::NotRequired,
                'deadline_in_days' => 6,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['الفنون والتصميم', 'الهندسة المعمارية', 'الآثار', 'الموسيقى'],
                'min_gpa' => 2.9, 'gpa_scale' => 4, 'acceptance_rate' => 19,
                'description' => 'منحة تقدّمها الحكومة الإيطالية للطلاب الأجانب لدراسة الماجستير والدكتوراه ودورات اللغة الإيطالية، مع مخصّص شهري وإعفاء من الرسوم.',
                'eligibility' => [
                    'ألا يتجاوز العمر 28 عاماً لبرامج الماجستير.',
                    'شهادة لغة إيطالية أو إنجليزية حسب البرنامج.',
                    'سجل أكاديمي جيد.',
                    'ملف أعمال للتخصصات الفنية.',
                ],
                'documents' => array_slice(self::COMMON_DOCS, 0, 4),
                'benefits' => self::PARTIAL_BENEFITS,
            ],
            // --- منح بحالات إدارية مختلفة لاختبار لوحة الإدارة ---
            [
                'title_ar' => 'منحة مؤسسة المستقبل للبحث العلمي',
                'title_en' => 'Future Foundation Research Grant',
                'provider' => 'مؤسسة المستقبل',
                'country_code' => 'AE',
                'country_name_ar' => 'الإمارات',
                'region' => 'الشرق الأوسط',
                'funding_type' => FundingType::Partial,
                'language_requirement' => LanguageRequirement::NotRequired,
                'status' => ScholarshipStatus::PendingReview,
                'deadline_in_days' => 120,
                'levels' => [DegreeLevel::Master, DegreeLevel::Phd],
                'majors' => ['الذكاء الاصطناعي وتعلم الآلة', 'الفضاء', 'الاستدامة البيئية'],
                'description' => 'منحة بحثية لدعم مشاريع البحث في مجالات التقنيات الناشئة. البيانات قيد المراجعة.',
                'eligibility' => ['مقترح بحثي مفصّل.', 'إشراف أكاديمي معتمد.'],
                'documents' => array_slice(self::COMMON_DOCS, 0, 3),
                'benefits' => self::PARTIAL_BENEFITS,
            ],
            [
                'title_ar' => 'منحة التميّز الرقمي',
                'title_en' => 'Digital Excellence Scholarship',
                'provider' => 'مبادرة التحول الرقمي',
                'country_code' => 'QA',
                'country_name_ar' => 'قطر',
                'region' => 'الشرق الأوسط',
                'funding_type' => FundingType::TuitionOnly,
                'language_requirement' => LanguageRequirement::NotRequired,
                'status' => ScholarshipStatus::Draft,
                'deadline_in_days' => 160,
                'levels' => [DegreeLevel::Bachelor],
                'majors' => ['علوم الحاسوب', 'الأمن السيبراني'],
                'description' => 'مسودة منحة قيد الإعداد — بانتظار استكمال بيانات الجهة المانحة والمزايا.',
                'eligibility' => ['قيد الإعداد.'],
                'documents' => [],
                'benefits' => [],
            ],
        ];
    }
}
